Omnivus-2/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Omnivus_2.Models.Data;

namespace Omnivus_2.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        private readonly AppDbContext _context;

        public AdminController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Users()
        {
            
            return View(await _context.Profiles.Include(x => x.User).ToListAsync()); //lista över profiler
        }
    }
}

Omnivus-2/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Omnivus_2.Models;
using Omnivus_2.Models.Forms;
using Omnivus_2.Services;

namespace Omnivus_2.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        //hantera roller
        private readonly RoleManager<IdentityRole> _roleManager;
        //hantera profil
        private readonly IProfileManager _profileManager;

        public AuthenticationController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager, IProfileManager profileManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _profileManager = profileManager;
        }

        #region Signup

        [Route("signup")]
        [HttpGet]
        public IActionResult SignUp(string returnUrl =null)
        {
            if (_signInManager.IsSignedIn(User)) //Om användaren är inloggad->redirect to home
                return RedirectToAction("Index", "Home");

            var form=new SignUpForm();

            if(returnUrl !=null)
                form.ReturnUrl = returnUrl;

            return View(form);
        }



        [Route("signup")]
        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpForm form)
        {
            if (ModelState.IsValid) //Check if form is valid
            {
                if (!await _roleManager.Roles.AnyAsync()) //if no roles exist
                {
                    await _roleManager.CreateAsync(new IdentityRole("admin"));
                    await _roleManager.CreateAsync(new IdentityRole("user"));
                }

                if (!await _userManager.Users.AnyAsync()) //if no users been created,make first user admin
                    form.RoleName = "admin";


                var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Email == form.Email);//check if email allready exist
                if (user == null)
                {
                    user = new IdentityUser() //create new identity with uniq email
                    {
                        UserName = form.Email,
                        Email = form.Email
                    };

                    var userResult = await _userManager.CreateAsync(user, form.Password); //create user with password
                    if (userResult.Succeeded)
                    {
                        await _userManager.AddToRoleAsync(user, form.RoleName); //Add role to user 

                        var profile = new UserProfile //create new profile
                        {
                            FirstName = form.FirstName,
                            LastName = form.LastName,
                            Email = user.Email,
                            StreetName = form.StreetName,
                            PostalCode = form.PostalCode,
                            City = form.City,
                            Country = form.Country
                        };

                        var profileResult = await _profileManager.CreateAsync(user, profile); //create  profile
                        if (profileResult.Succeeded)
                        {
                            await _signInManager.SignInAsync(user, isPersistent: false);

                            if (form.ReturnUrl == null || form.ReturnUrl == "/")
                                return RedirectToAction("Index", "Home");
                            else
                                return LocalRedirect(form.ReturnUrl);
                        }
                        else
                        {
                            form.ErrorMessage = "There was a problem when creating your profile. Please sign in and complete your profile registration";
                        }
                    }
                }
                else
                {
                    form.ErrorMessage = "A user with the same e-mail address already exists";
                }

            }

            return View();
        }



        #endregion

        #region SignIn

        [Route("signin")]
        [HttpGet]
        public IActionResult SignIn(string returnUrl = null)
        {
            if (_signInManager.IsSignedIn(User))
                return RedirectToAction("Index", "Home");

            var form = new SignInForm();
            if (returnUrl != null)
                form.ReturnUrl = returnUrl;

            return View(form);
        }


        [Route("signin")]
        [HttpPost]
        public async Task<IActionResult> SignIn(SignInForm form)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(form.Email, form.Password, isPersistent: false, false);
                if (result.Succeeded)
                {
                    if (form.ReturnUrl == null || form.ReturnUrl == "/")
                        return RedirectToAction("Index", "Home");
                    else
                        return LocalRedirect(form.ReturnUrl);
                }
            }

            form.ErrorMessage = "Incorrect email or password";
            return View(form);
        }



        #endregion 

        [Route("signout")]
        [HttpGet]
        public async Task<IActionResult> SignOut()
        {
            if (_signInManager.IsSignedIn(User))
                await _signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }

        [Route("access-denied")]
        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

    }
}

Omnivus-2/Views/Shared/_ContactFormPartial.cshtml
<div id="Contact">
    <div class="container container-padding">
        <div class="row ">
            <div class=" contactUsForm col">
                <div class="container ">
                    <div id="contact-text" class="position-relative">
                        <span>Get In Touch</span>
                        <img src="/images/line.svg" class="position-absolut">
                        <h1>
                            Estimate for your
                            projects.
                        </h1>
                    </div>


                    <form class="needs-validation" onsubmit="onSubmit()" novalidate>
                        <div class="row">
                            <div class="col">
                                <input type="text" class="form-control validation input-border button-off" placeholder="Enter your name" required>
                                <div class="invalid-feedback">
                                    Du måste ange minst 2 bokstäver
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <input type="email" class="form-control validation input-border button-off" placeholder="Enter your email" required>
                                <div class="invalid-feedback">
                                    Du måste ange gilltig epost-adress
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <textarea type="textarea" class="form-control validation input-border button-off" rows="6" placeholder="Enter your questions & subject here." required></textarea>
                                <div class="invalid-feedback">
                                    Du måste ange minst 2 bokstäver
                                </div>
                            </div>
                        </div>
                        <div class="row ">
                            <div class="col btn-form">
                                <button type="submit" class="btn btn-primary submit">Submit Now</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="contact-img col ">
                <img src="/images/block.svg">
            </div>
        </div>
    </div>
</div>

Omnivus-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - omniVus</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    @RenderBody()
    <partial name="_footPartial" />


    <!-- JavaScript Bundle with Popper -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Omnivus-2/Views/Shared/_Navbar.cshtml
 
<!-- header -->
<div class="header-grid">
    <div id="branding">
        <h1>OmniVus.</h1>
        <p>IT Service & Technology</p>
    </div>
    <nav id="top-menu">
        @if (SignInManager.IsSignedIn(User))
        {
            
            <a asp-controller="Profile" asp-action="Index" asp-route-id="@User.FindFirst("UserId").Value">@await ProfileManager.DisplayNameAsync(User.FindFirst("UserId").Value) 
                <br/>
                <p>@await ProfileManager.DisplayRoleAsync(User.FindFirst("UserId").Value)</p>
                </a>
                
            
            <div class="social">
                @if(User.IsInRole("admin"))
                {
                   <a asp-controller="Admin" asp-action="Users">Users</a> 
                }
            
            <a asp-controller="Authentication" asp-action="SignOut" >Sign out</a>
        </div>

        }
        else
        {
        <a href="mailto:info@domain.com">info@domain.com</a>
        <div class="social">
            <a href="https://facebook.com">facebook</a>
            <a href="https://twitter.com">twitter</a>
            <a href="https://linkedin.com">linkedin</a>
            <a href="https://youtube.com">youtube</a>
        </div>
        }
        
    </nav>
    <nav id="main-menu">
        <div class="menu-items">
            
            <a asp-controller="Home" asp-action="Index">Home</a>
            <a asp-controller="Home" asp-action="Services">Services</a>
            <a asp-controller="Home" asp-action="Contact">Contact</a>
        </div>
        @if (!SignInManager.IsSignedIn(User))
        {
            <a asp-controller="Authentication" asp-action="SignIn" class="btn btn-main">Sign in</a>
        }  
    </nav>
</div>

Omnivus-2/Views/Shared/_ServicesPartial.cshtml
<div id="services">
    <div class=" container container-padding">
        <div class="Services-content">
            <div class="card-deck">
                <div class="row">
                    <div class="col">
                        <div class="card position-relative">
                            <img class="card-img-top" src="" alt="">
                            <div class="card-body">
                                <h5 class="card-title">UI/UX Design</h5>

                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <img class="card-img-top" src="" alt="">
                            <div class="card-body">
                                <h5 class="card-title">IT Consultancy</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <img class="card-img-top" src="" alt="">
                            <div class="card-body">
                                <h5 class="card-title">Technology Prof.</h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row2">
                    <div class="col">

                        <div class="card">
                            <img class="card-img-top" src="" alt="">
                            <div class="card-body">
                                <h5 class="card-title">Web Development</h5>
                            </div>
                        </div>

                    </div>
                    <div class="col">
                        <div class="card">
                            <img class="card-img-top" src="" alt="">
                            <div class="card-body">
                                <h5 class="card-title">App Development</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <img class="card-img-top" src="" alt="">
                            <div class="card-body">
                                <h5 class="card-title">Game Design</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Omnivus-2/Views/Shared/_SignUpFormPartial.cshtml
@using Omnivus_2.Models.Forms
@model SignUpForm

<div id="sign-up">
    <div class="forms-text text-center">
        <h1>Sign up</h1>
        <p>Have you already an account? <a asp-controller="Authentication" asp-action="SignIn">Sign in.</a></p>
    </div>
    <form asp-action="SignUp" asp-route-returnUrl="@Model.ReturnUrl">
        <div class="row">
            <div class="col">
                <input asp-for="FirstName" class="form-control input-border" placeholder="FirstName">
                <span asp-validation-for="FirstName" class="form-text text-danger"></span>
            </div>
            <div class="col">
                <input asp-for="LastName" class="form-control input-border" placeholder="Lastname">
                <span asp-validation-for="LastName" class="form-text text-danger"></span>
            </div>
        </div>
        
        <div class="row">
            <div class="col">
                <input asp-for="StreetName" class="form-control  input-border" placeholder="Streetname">
                <span asp-validation-for="StreetName" class="form-text text-danger"></span>
            </div>
            <div class="col">
                <input asp-for="PostalCode" class="form-control input-border" placeholder="PostalCode">
                <span asp-validation-for="PostalCode" class="form-text text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input asp-for="City" class="form-control input-border" placeholder="City">
                <span asp-validation-for="City" class="form-text text-danger"></span>
            </div>
            <div class="col">
                <input asp-for="Country" class="form-control input-border " placeholder="Country">
                <span asp-validation-for="Country" class="form-text text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input asp-for="Email" class="form-control  input-border" placeholder="Email">
                <span asp-validation-for="Email" class="form-text text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input asp-for="Password" class="form-control input-border" placeholder="Password">
                <span asp-validation-for="Password" class="form-text text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input asp-for="VerifyPassword" class="form-control input-border" placeholder="Verify password">
                <span asp-validation-for="VerifyPassword" class="form-text text-danger"></span>
            </div>
        </div>
        <div class="row ">
            <div class="col d-grid mb-3 btn-form text-center">
                <button type="submit" class="btn btn-primary">Sign up</button>
                <br/>
                <p class="text-danger">@Model.ErrorMessage </p>
                 <p>Have you already an account? <a asp-controller="Authentication" asp-action="SignIn">Sign in.</a></p>
            </div>
        </div>
    </form>
</div>

Omnivus-2/Views/Shared/_aboutUsPartial.cshtml
<div id="about-us">
    <div class="container container-padding">
        <div class="flex">
            <div class="column-center">
                <img src="images/block-about.svg">
            </div>
            <div class="column-center">
                <div id="about-text" class="position-relative">
                    <span>About Us </span>
                    <img src="/images/line.svg" class="position-absolut">
                    <h1>You can't use up creativity.</h1>
                    <p>Does any industry face a more complex audience journey and marketing sales process than B2B technology? Consider the number of people who influence a sale, the length of the decision-making cycle, the competing interests of the people who purchase, implement, manage, and use the technology. It’s a lot meaningful content here.</p>
                    <div class="flex position-relative">
                        <img src="/images/bg.svg" class="position-absolut">
                        <h2>15</h2>
                        <h3>Years Of <br>Experience</h3>
                    </div>
                    <button class="btn btn-main">Learn More</button>
                    <button class="btn btn-main">video Intro Video</button>
                </div>
            </div>
        </div>
    </div>
</div>

Omnivus-2/Views/Shared/_footPartial.cshtml
<div id="footer">

    <div class="container container-padding">
        <img id="footer-img-1" src="/images/dotts-small.svg">
        <img id="footer-img-2" src="/images/dot-big.svg">
        <div class="items">
            <div id="footer-1">
                <h1>OmniVus.</h1>
                <p>
                    The web has changed a lot since we posted our first article back in 2007. The team at Mattin-Lassi Group has changed too, as have the things that we bring to our community
                    conferences, books, and our membership added to the online magazine.
                </p>
                <p>One thing that hasn’t changed is that we’re a small team — with most of us not working</p>
            </div>
            <div id="footer-2">
                <h2>Working Hours</h2>
                <ul>
                    <li>Monday - Friday: 7:00 - 17:00</li>
                    <li>Saturday: 7:00 - 12:00</li>
                    <li>Sunday and holidays: 8:00 - 10:00</li>
                </ul>
                <div> <p><span class="white-text">For more then 15 years,</span> IT Service has been a reliable partner in the field of logistics and cargo forwarding.</p></div>
            </div>
        </div>
        <div id="footer-3" class="">
            <p>Copyright © Mattin-Lassei Group AB - 2022</p>
        </div>
    </div>
</div>

Omnivus-2/Views/Shared/_formPartial.cshtml
<div class="container container-padding">
    <div id="form" class="">
        <div class="container ">
            <div class="text-center">
                <h1>Book a Meeting</h1>
                <p>
                    Does any industry face a more complex audience journey and
                    <br>
                    marketing sales process than B2B technology.
                </p>
            </div>
            <form class="needs-validation" onsubmit="onSubmit()" novalidate>
                <div class="row">
                    <div class="col">
                        <input type="text" class="form-control validation input-border button-off" placeholder="Enter your name" required>
                        <div class="invalid-feedback">
                            Du måste ange minst 2 bokstäver
                        </div>
                    </div>

                    <div class="col">
                        <input type="email" class="form-control validation input-border button-off" placeholder="Enter your email" required>
                        <div class="invalid-feedback">
                            Du måste ange gilltig epost-adress
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <textarea type="textarea" class="form-control validation input-border button-off" rows="7" placeholder="Enter your questions & subject here." required></textarea>
                        <div class="invalid-feedback">
                            Du måste ange minst 2 bokstäver
                        </div>
                    </div>
                </div>
                <div class="row ">
                    <div class="col btn-form">
                        <button type="submit" class="btn btn-primary submit">Book a Meeting Now</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Omnivus-2/Views/Shared/_introPartial.cshtml
<div id="intro">
    <div class="container container-padding">
        <div class="flex">
            <div class="column-center">
                <div id="intro-text" class="position-relative">
                    <span>Intro</span>
                    <img src="/images/line.svg" class="position-absolut">
                    <h1>How we growth our business.</h1>
                    <h5>The introduction of cloud and mobile technologies into enterprise software.</h5>
                    <p>hether you are building an enterprise web portal or a state-of-the-art website, you always need the right modern tools. Well-built and maintained .NET frameworks provide those tools in abundance, allowing maintained .NET frameworks provide those tools in abundance, allowing developers to save time, re-use code, and streamline the back end. As software development tools continuously.</p>
                    <button class="btn btn-main">Learn More</button>
                </div>
            </div>
            <div class="column-center">
                <img src="images/block.svg">
            </div>
        </div>
    </div>
</div>

Omnivus-2/Views/Shared/_showcasePartialView.cshtml
<!-- showcase -->
<div class="container container-padding">
    <section id="showcase">
        <div class="column">
            <div class="content">
                <p>Promote any product, service or online course.</p>
                <h1>Get every it Services Here</h1>
                <div class="items">
                    <div class="item">
                        <img src="images/red-circle.svg" alt="">
                        <span>IT Product</span>
                    </div>
                    <div class="item">
                        <img src="images/blue-circle.svg" alt="">
                        <span>IT Services</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="column">
            <img class="showcase-image" src="images/person-male.svg" alt="">
        </div>
    </section>
</div>